[package]
name = "context"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]

[dependencies]
futures = "0.1"

[dev-dependencies]
tokio-timer = { git = "https://github.com/tokio-rs/tokio-timer" }
